# —— 基础画质 —— 
profile=gpu-hq
vo=gpu-next
hwdec=yes

# —— OSD/窗口（配合 uosc）——
osc=no
osd-bar=no
border=no

# —— 恢复/历史 —— 
save-position-on-quit=yes
save-watch-history=yes
# 把真实文件名写进 watch_later 便于 g-w 菜单识别（注意隐私）
write-filename-in-watch-later-config=yes

# —— 字幕/语言（按需改：简中/繁中/英/日）——
slang=eng,jpn,chi,chs,cht
alang=eng,jpn,chi

# —— 其它常用 —— 
# 更顺滑的UI绘制（uosc 建议项）
# video-sync=display-resample